---
title: "p8105 HW4 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

Column {data-width=550}
-----------------------------------------------------------------------

```{r}
data("instacart")

instacart = 
  instacart %>% 
  select(order_id, order_hour_of_day, reordered, product_id, product_name, department) %>%
  sample_n(10000)
```

### Top Departments

```{r}
instacart %>% 
  count(department) %>% 
  mutate(
    department = fct_reorder(department, n)) %>%
  plot_ly(
    x = ~department, y = ~n, color = ~department,
    type = "bar", colors = "viridis")
```


Column {data-width=450}
-----------------------------------------------------------------------

### Time of Day Orders were Placed by Department

```{r}
instacart %>% 
   mutate(
    department = fct_reorder(department, order_hour_of_day)) %>%
  plot_ly(
    x = ~department, y = ~order_hour_of_day, color = ~department,
    type = "box", colors = "viridis")
```

### Proportion of Items Reordered

```{r}
instacart %>% 
  group_by(product_name) %>% 
  summarize(proportion_reordered = mean(reordered), n=n()) %>% 
  plot_ly(
    x = ~n, y = ~proportion_reordered,
    alpha = .5, type = "scatter", mode = "markers")
```

