---
title: "Plotly"
author: Meghan Bellerose
date: October 26, 2020
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

# Loading Data

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Upload and make dataset smaller

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    price %in% 100:500,
    room_type == "Entire home/apt"
  ) %>% 
  drop_na(rating)

```

# Plotly plots

## Scatterplot

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nRating:", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long,  color = ~price, text = ~text_label,
    alpha = .5, type = "scatter", mode = "markers")
```

## Boxplot

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    y = ~price, x = ~neighbourhood, color = ~neighbourhood,
    type = "box", colors = "viridis")
```
## Bar plot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood,
    type = "bar", colors = "viridis")
```

Look at plotlyr.com for other ideas

# Convert to ggplot using ggplotly

```{r}
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```


```{r}
box_ggplot = 
  nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price, fill = neighbourhood)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```

# Fleshdashboard 

